[tool.autohooks]
mode = 'venv'
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.isort"]

[tool.autohooks.plugins.black]
arguments = ["--check"]

[tool.autohooks.plugins.isort]
include = ['src/*.py', '*.py']

[tool.isort]
profile = "black"
